
use master;
-- tables

CREATE DATABASE dbRIFA
GO
USE dbRIFA
GO
-- Table: GANADOR
CREATE TABLE GANADOR (
    IDGAN int  identity (1,1) NOT NULL,
    IDRIF int  NOT NULL,
    CODPRE char(1)  NOT NULL,
    CONSTRAINT GANADOR_pk PRIMARY KEY  (IDGAN)
);

-- Table: PARTICIPANTE
CREATE TABLE PARTICIPANTE (
    IDPAR int  identity (1,1) NOT NULL,
    NOMPAR varchar(50)  NOT NULL,
    APEPAR varchar(50)  NOT NULL,
    CELPAR char(9)  NOT NULL,
    ESTPAR char(1)  NOT NULL,
    CONSTRAINT PARTICIPANTE_pk PRIMARY KEY  (IDPAR)
);

-- Table: PREMIO
CREATE TABLE PREMIO (
    CODPRE char(1)  NOT NULL,
    DESPRE varchar(200)  NOT NULL,
    CONSTRAINT PREMIO_pk PRIMARY KEY  (CODPRE)
);

-- Table: RIFA
CREATE TABLE RIFA (
    IDRIF int identity (1000,1) NOT NULL,
    IDPAR int  NOT NULL,
    CONSTRAINT RIFA_pk PRIMARY KEY  (IDRIF)
);

-- foreign keys
-- Reference: GANADOR_PREMIO (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_PREMIO
    FOREIGN KEY (CODPRE)
    REFERENCES PREMIO (CODPRE);

-- Reference: GANADOR_RIFA (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_RIFA
    FOREIGN KEY (IDRIF)
    REFERENCES RIFA (IDRIF);

-- Reference: RIFA_PARTICIPANTE (table: RIFA)
ALTER TABLE RIFA ADD CONSTRAINT RIFA_PARTICIPANTE
    FOREIGN KEY (IDPAR)
    REFERENCES PARTICIPANTE (IDPAR);

