-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-05-16 00:14:32.881

-- tables
-- Table: GANADOR
CREATE TABLE GANADOR (
    CODGAN int  NOT NULL,
    CODRIF char(4)  NOT NULL,
    CODPRE char(1)  NOT NULL,
    CONSTRAINT GANADOR_pk PRIMARY KEY  (CODGAN)
);

-- Table: PARTICIPANTE
CREATE TABLE PARTICIPANTE (
    CODPAR int  NOT NULL,
    NOMPAR varchar(50)  NOT NULL,
    APEPAR varchar(50)  NOT NULL,
    CELPAR char(9)  NOT NULL,
    ESTPAR char(1)  NOT NULL,
    CONSTRAINT PARTICIPANTE_pk PRIMARY KEY  (CODPAR)
);

-- Table: PREMIO
CREATE TABLE PREMIO (
    CODPRE char(1)  NOT NULL,
    DESPRE varchar(200)  NOT NULL,
    CONSTRAINT PREMIO_pk PRIMARY KEY  (CODPRE)
);

-- Table: RIFA
CREATE TABLE RIFA (
    CODRIF char(4)  NOT NULL,
    CODPAR int  NOT NULL,
    CONSTRAINT RIFA_pk PRIMARY KEY  (CODRIF)
);

-- foreign keys
-- Reference: GANADOR_PREMIO (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_PREMIO
    FOREIGN KEY (CODPRE)
    REFERENCES PREMIO (CODPRE);

-- Reference: GANADOR_RIFA (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_RIFA
    FOREIGN KEY (CODRIF)
    REFERENCES RIFA (CODRIF);

-- Reference: RIFA_PARTICIPANTE (table: RIFA)
ALTER TABLE RIFA ADD CONSTRAINT RIFA_PARTICIPANTE
    FOREIGN KEY (CODPAR)
    REFERENCES PARTICIPANTE (CODPAR);

-- End of file.

